import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiOutlineMail,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from "react";
import web1 from "../public/web1.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bendaas Houssem Eddine portfolio</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <a className="text-xl font-burtons dark:text-white" href="">
            B-Houssem
            </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white dark:text-black px-4 py-2 rounded-md ml-8"
                  href="/resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Bendaas Houssem Eddine
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Fullstack Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">
              {" "}
              I'm a highly motivated developer with a Masters degree in Software
              Engineering. My passion lies in crafting robust and efficient
              software solutions. With a strong foundation in Java, JavaScript,
              and TypeScript, I enjoy exploring the exciting possibilities
              offered by frameworks like Spring Boot, Angular, and React.
              Continuously expanding my knowledge, I stay updated with the
              latest industry trends and best practices. I strive to deliver
              clean and elegant code while maintaining a focus on scalability
              and performance. Let's connect and explore opportunities to
              collaborate on exciting projects!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
          <a href="https://github.com/B-Houssem"><AiFillGithub /></a>
            <a href="https://www.linkedin.com/in/houssem-eddine-bendaas-11319425b/"><AiFillLinkedin /></a>
            <a href="mailto:houssembendaas00@gmail.com"><AiOutlineMail /></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Over the course of my academic and professional career, I have acquired a vast amount of expertise and skills in both front-end and back-end development, using a variety of tools and frameworks. I always aim to expand my horizons and further deepen my knowledge within the ever-evolving field of web development.
            </p>
          </div>
          <div className="lg:flex  gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-blue-950 to-blue-500 w-full hover:w-screen">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Frontend Development
              </h3>
              <p className="py-2 dark:text-gray-400">
                Creating responsive websites tailor made to fit your needs.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-black">
                Technologies I use
              </h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                HTML, CSS, Javascript
              </p>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                Angular/ React
              </p>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                TailwindCSS
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-blue-950 to-blue-500 w-full hover:w-screen">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Backend development
              </h3>
              <p className="py-2 dark:text-gray-400">
                Creating Java based REST APIs using the springboot framework.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-black">
                Technologies I use
              </h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                Java, MySQL, PostgresSQL
              </p>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                Springboot
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-blue-950 to-blue-500 w-full hover:w-screen">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Consulting
              </h3>
              <p className="py-2 dark:text-gray-400">
                provide consulting for optimazing existing software, and
                conceptualizing new ones, and managing projects.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-black">
                Technologies I use
              </h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">Scrum</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">UML</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">
                Microsoft Project
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since the beginning of my journey as a freelance developer, I've done personal projects as well as remote work for
              <span className="text-teal-500"> a startup </span>
              called <span className="text-teal-500">Safe Digital Health </span>
              in collaboratation with talanted people to create digital products for both business and consumer use.
            </p>
                
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}
